baseURL: "/"
languageCode: en-us
defaultContentLanguage: en
title: Things You Can Add To A Personal Site
description: Every single thing I could think of, except my professional secrets.

taxonomies:
  tag: "tags"
  category: "categories"

permalinks:
  guides: /:filename/
  lists: /:filename/
  writing: /:filename/

imaging:
  quality: 99

enableRobotsTXT: true

minify:
  minifyOutput: true

outputs:
  home:
    - html
    - rss
    - json
  page:
    - html
    - json

tdewolff:
    css:
      keepCSS2: true
      precision: 0
    html:
      keepComments: false
      keepConditionalComments: true
      keepDefaultAttrVals: true
      keepDocumentTags: true
      keepEndTags: true
      keepQuotes: false
      keepWhitespace: false
    js:
      keepVarNames: false
      noNullishOperator: false
      precision: 0
    json:
      keepNumbers: false
      precision: 0
    svg:
      keepComments: false
      precision: 0
    xml:
      keepWhitespace: false

disableKinds:
- sitemap

params:
  AuthorName: Judah
  GitHubUser: stealsocks
  description: Every single thing I could think of, except my professional secrets.
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  katex: true
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: true
  defaultDarkTheme: false
  moveFooterToHeader: false

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: true
        title: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 3
    startLevel: 2

related:
  includeNewer: true
  indices:
  - name: keywords
    weight: 100
  - name: date
    weight: 10
  threshold: 80
  toLower: true